### ISSUE TITLE
PyMPDATA and PyMPDATA-examples merge checklist

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/MPyDATA#393]
- [x] sort out pdoc upload (currently examples overwrite main content on PyMPDATA repo)
- [x] introduce index.html for pdoc to pick PyMPDATA or examples
- [x] fix links to documentation to include PyMPDATA or PyMPDATA_examples prefix
- [x] phase out tests within examples
- [x] add "./PyMPDATA-examples" to test dependencies and reduce pip-install invocations in CI workflow file
- [x] replace submodule with examples repo contents
- [x] rename `PyMPDATA-examples` to `examples`
- [x] use devops_tests
- [ ] old repo: add PyMPDATA and PyMPDATA-examples version specification within notebooks and examples setup.py
- [ ] old repo: add a note within example README that the examples were moved
- [ ] old repo: archive examples repo (adding a note in the README)
- [ ] fix notebook links in the README
- [ ] fix badge links in notebooks
- [ ] check if notebooks work on colab
- [ ] check if notebooks work on mybinder
- [x] remove notebooks from wheels!
- [ ] cleanup README from obsolete examples references
- [x] examples README (for PyPI web)
- [ ] populate notebook output (temporarily cleared to avoid filling PyMPDATA repo history with obsolate large plots)!

related:
- [ ] parallel test execution
- [ ] switch to pyproject.toml
- [x] switch from pdoc3 to pdoc

**Comment by slayoo** [comment]
all what was reasonably needed to be done here is done, closing
